get_video_speed_form:
    path:     /getVideoSpeed
    defaults: { _controller: PlayBannerBundle:Default:getVideoSpeed }
    methods:  POST
    
set_video_speed_form:
    path:     /setVideoSpeed
    defaults: { _controller: PlayBannerBundle:Default:setVideoSpeed }
    methods:  POST