imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@HomeBundle/Resources/config/services.yml" }
    - { resource: "@VideoBundle/Resources/config/services.yml" }
    - { resource: "@ConfigurationBundle/Resources/config/services.yml" }
    - { resource: "@MediaBundle/Resources/config/services.yml" }
    - { resource: "@ArtistBundle/Resources/config/services.yml" }
    - { resource: "@ListBundle/Resources/config/services.yml" }
    - { resource: "@DataminingBundle/Resources/config/services.yml" }
    - { resource: "@SearchengineBundle/Resources/config/services.yml" }
    - { resource: "@PremiumBundle/Resources/config/services.yml" }
    - { resource: "@PlayBannerBundle/Resources/config/services.yml" }
    - { resource: "@PresentationBundle/Resources/config/services.yml" }
    - { resource: "@SessionBundle/Resources/config/services.yml" }
    - { resource: "@OptionsBundle/Resources/config/services.yml" }
    - { resource: "@HistoryBundle/Resources/config/services.yml" }
    - { resource: "@CacheBundle/Resources/config/services.yml" }
    - { resource: "@UploadVideoBundle/Resources/config/services.yml" }
    - { resource: "@SongBundle/Resources/config/services.yml" }
    - { resource: "@CommentVideoBundle/Resources/config/services.yml" }
    - { resource: "@EditProfileBundle/Resources/config/services.yml" }
    - { resource: "@FollowerBundle/Resources/config/services.yml" }
    - { resource: "@FollowingBundle/Resources/config/services.yml" }
    - { resource: "@EditVideoBundle/Resources/config/services.yml" }
    - { resource: "@UserReportsBundle/Resources/config/services.yml" }
    - { resource: "@PaypalBundle/Resources/config/services.yml" }
    - { resource: "@EditLyricsBundle/Resources/config/services.yml" }
    - { resource: "@ShowLyricsBundle/Resources/config/services.yml" }
    - { resource: "@PayUBundle/Resources/config/services.yml" }
    - { resource: "@DeleteVideoBundle/Resources/config/services.yml" }
    - { resource: "@EditInformationVideoBundle/Resources/config/services.yml" }
    - { resource: "@PromoteVideoBundle/Resources/config/services.yml" }
    - { resource: "@AdvertisingVideoBundle/Resources/config/services.yml" }
    - { resource: "@DeclineDeleteVideoBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
