read_lyrics_form:
    path:     /readLyrics
    defaults: { _controller: VideoBundle:Default:readLyrics }
    methods:  POST
    
get_closedCaption_form:
    path:     /getClosedCaption
    defaults: { _controller: VideoBundle:Default:getClosedCaption }
    methods:  POST
    
set_closedCaption_form:
    path:     /setClosedCaption
    defaults: { _controller: VideoBundle:Default:setClosedCaption }
    methods:  POST
    
delete_specific_closedCaption_form:
    path:     /deleteSpecificClosedCaption
    defaults: { _controller: VideoBundle:Default:deleteSpecificClosedCaption }
    methods:  POST